### PR TITLE
fix issue with difference between gradient and interpolatecolors

### PR DESCRIPTION
**Pull request by WajdiMuh**
#3 this pull request fixes this issue that is caused by the linear gradient not equally spacing colors

### CODE REVIEW

**Comment by WajdiMuh** [comment]
i also added a fix for tapping on the color picker since onEnd of teh tap recognizer was called before the animation would end causing it to report the old value so i added a callback for the circle animation ending and there i called onEnd

**Comment by WajdiMuh** [comment]
any updates regarding this pull request?

**Comment by Bayramito** [comment]
> #3 this pull request fixes this issue that is caused by the linear gradient not equally spacing colors

Thank you for your effor but your solution isn't working properly.

**Comment by Bayramito** [comment]
> i also added a fix for tapping on the color picker since onEnd of teh tap recognizer was called before the animation would end causing it to report the old value so i added a callback for the circle animation ending and there i called onEnd

This is not a behavior that i wanted. I also thought that while developing but between finishing and onStart there is a littie small gap on which, color returning null and this is breaking the onChanging prope where you need to get the value nonstop

**Pull request closed without merging**
